name: MavenTests
on: [push]
permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      -
        name: Maven Test
        run: mvn test